### ISSUE TITLE
[Task] Create an axios instance with token management 

### ISSUE THREAD

**Issue by JRB958** [SOEN490-SportsApp/SportsApp#114]
### Description
Create a custom Axios instance that includes automatic token management and centralized error handling. This will improve API request consistency and ensure users receive clear feedback for common errors (e.g., network issues, authentication errors). Write tests to ensure proper functionality 

---

### Tasks

- [x] Set up Axios Instance
- [x] Implement Token Management
- [x] Use centralize Alerts
- [x] Test the instance

---

### Testing plan 

- [ ] include a testing plan to use the instance in all the subsequent jest testing
