### ISSUE TITLE
11.1 Authentication and authorization on microservices [backend]

### ISSUE THREAD

**Issue by walidoow** [SOEN490-SportsApp/SportsApp#181]
# Implement Authentication and Authorization for All Microservices

### Description
As a Sporta developer, I want to set up authentication and authorization for all microservices to ensure that only authenticated users can access the system, permissions are enforced based on roles, and users can only manage events they created or view their own profiles.

**Story Points:** 13  
**Priority:** P1  
**Risk:** High  

### Requirements

1. **Authentication Setup**:
   - Use **Keycloak** as the identity provider for centralized authentication.
   - Configure each microservice to validate JSON Web Tokens (JWTs) issued by Keycloak.
   - Use the `Authorization` header (`Bearer <token>`) to authenticate requests.
   - Extract user information (e.g., user ID, roles) from the JWT claims.

2. **Authorization Configuration**:
   - Implement **Role-Based Access Control (RBAC)** using roles defined in Keycloak:
     - Define roles such as `user` and `admin`.
     - Associate permissions with roles (e.g., users can only manage their own data, and admins can access all resources).
   - Enforce role-specific permissions at the endpoint level using annotations like `@PreAuthorize`.

3. **Profile Access Control**:
   - Implement a `/users/{userId}` endpoint to allow users to view their own profiles.
   - Enforce ownership by checking that the `userId` in the request matches the `userId` in the JWT claims:
     ```java
     @PreAuthorize("#userId == authentication.principal.userId or hasRole('ROLE_ADMIN')")
     ```
   - Ensure that admins can bypass this restriction and view any user profile.

4. **Event Management Access Control**:
   - Ensure users can only edit or delete events they have created:
   - Admins can bypass ownership restrictions and manage all events.

5. **Public and Private Endpoints**:
   - Secure all private endpoints to ensure only authenticated users can access them.
   - Apply ownership and role-based restrictions for profile and event-related operations.

6. **Keycloak Integration**:
   - Configure Keycloak to include user roles and IDs in the JWT.

7. **Testing and Documentation**:
   - Write unit tests for token validation, role-based access control, and ownership checks.
   - Write integration tests to verify authentication and authorization workflows.
   - Document the authentication and authorization setup, including roles, token structure, and required headers, in the project wiki and Swagger.

---

### Key Features to Implement

1. **Profile Access Control**:
   - Add a `/users/{userId}` endpoint for retrieving user profile details.
   - Secure the endpoint so users can only view their own profiles:
     ```java
     @PreAuthorize("#userId == authentication.principal.userId or hasRole('ROLE_ADMIN')")
     ```
   - Extract `userId` from the JWT claims and verify it matches the requested `userId`.

2. **Granular Access Control**:
     - Secure endpoints for profile and event management:
     - Public endpoints (e.g., event browsing) remain accessible without authentication.
     - Private endpoints (e.g., managing events or viewing profiles) require authentication and ownership checks.

---

### Acceptance Criteria

- [x] Authentication is implemented using JWTs issued by Keycloak.
- [x] Role-based access control is enforced across all endpoints.
- [x] Users can view only their own profiles through the `/users/{userId}` endpoint.
- [x] Users can only edit or delete events they created.
- [x] Admins can view all profiles and manage all events.
- [x] Public endpoints remain accessible without authentication.
- [ ] Unit and integration tests cover authentication, role checks, and ownership restrictions.
- [ ] Documentation is updated to include role definitions, token details, and configuration steps.

---

### Task Breakdown

1. **Profile and Event Model Updates**:
   - Implement profile access logic in the `/users/{userId}` endpoint.

2. **Implement Access Control Logic**:
   - Secure endpoints using `@PreAuthorize` and ownership checks.
   - Add service-level ownership validation for profiles and events.

3. **Test Authentication and Authorization**:
   - Write unit tests for JWT validation and ownership logic.
   - Write integration tests to verify access control across microservices.

4. **Document the Implementation**:
   - Update Swagger to reflect secured endpoints.
   - Add usage examples and configuration details to the project wiki.

5. **Research and Report**:
   - Investigate best practices for integrating Keycloak with Spring Boot.
   - Document findings and implementation details in the issue comments.
