### ISSUE TITLE
1.26 Send Friend Request

### ISSUE THREAD

**Issue by walidoow** [SOEN490-SportsApp/SportsApp#190]
# Implement Send Friend Request

### Description
As a user, I want to send a friend request to another user using their username so that I can connect with them. The receiver will have a list of received friend requests, and the sender will have a list of pending friend requests they have sent.

**Story Points:**   
**Priority:** P2  
**Risk:** Low  

### Requirements

1. **Send Friend Request**:
   - **Endpoint**: `POST /users/{userId}/friends/requests` where `userId` is the sender.
   - **Description**: Allows a user to send a friend request to another user.
   - **Request Body**:
     ```json
     {
       "receiverUsername": "targetUsername"
     }
     ```
   - **Response**:
     ```json
     {
       "message": "Friend request sent successfully.",
       "status": "pending"
     }
     ```
   - If the user is not found, return an appropriate error message.
   - If the sender is already friends with the receiver or has already sent a request, return a suitable message indicating the current status (e.g., already friends or request already sent).

2. **Security Considerations**:
   - Ensure only authenticated users can send, receive, and manage friend requests.
   - Validate that users cannot send requests to themselves.

### Acceptance Criteria

- [ ] The `/users/{userId}/friends/requests` endpoint allows a user to send a friend request to another user using their username.
- [ ] The request body contains the correct `receiverUsername` for the target user.
- [ ] A friend request is sent successfully.
- [ ] The system prevents a user from sending a request to themselves.

### Task Breakdown

1. **Send Friend Request Endpoint**:
   - Implement `POST /users/{userId}/friends/requests` to allow users to send a friend request.
   - Validate that the user exists and ensure the request isn't already pending or completed.

2. **Security & Validation**:
   - Ensure proper authentication and authorization are in place.
   - Validate inputs and prevent users from sending requests to themselves.

3. **Testing and Documentation**:
   - Write unit tests for the endpoint, covering edge cases (e.g., sending requests to self, duplicate requests).
   - Document the endpoint and its expected behavior using Swagger.
